# Generated by Django 6.0.6 on 2026-07-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_teacher_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="max_students",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Soft limit on active enrolled students. 0 means no cap.",
                verbose_name="Cupo máximo",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="is_waiting",
            field=models.BooleanField(
                default=False,
                help_text="True when the student is on the waiting list for their preferred group instead of enrolled.",
                verbose_name="En lista de espera",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="waiting_since",
            field=models.DateTimeField(
                blank=True,
                help_text="Auto-set the first time is_waiting is flipped on; used to prioritize assignments FIFO.",
                null=True,
                verbose_name="En espera desde",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["is_waiting"], name="students_is_wait_60da89_idx"),
        ),
    ]
