# Generated by Django 6.0.6 on 2026-07-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_waiting_list_and_group_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="sms_opt_in",
            field=models.BooleanField(
                default=False,
                help_text="v1.8: True if the parent has opted in to SMS notifications (payment reminders, urgent comms).",
                verbose_name="SMS opt-in",
            ),
        ),
    ]
