# Generated by Django 6.0.6 on 2026-07-02 17:26

import django.db.models.deletion
from django.db import migrations, models

import students.parent_portal_models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_add_parent_sms_opt_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentSessionToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "token",
                    models.CharField(default=students.parent_portal_models._fresh_token, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="session_tokens", to="students.parent"
                    ),
                ),
            ],
            options={
                "db_table": "parent_session_tokens",
                "indexes": [
                    models.Index(fields=["token"], name="parent_sess_token_bc198f_idx"),
                    models.Index(fields=["expires_at"], name="parent_sess_expires_1e9375_idx"),
                ],
            },
        ),
    ]
