# Generated by Django 6.0.6 on 2026-07-02 17:26

import secrets

import django.db.models.deletion
from django.db import migrations, models


def _fresh_token() -> str:
    """Historical default for the (since removed) `ParentSessionToken.token`.

    Inlined here because `students.parent_portal_models` no longer exists: the
    parent portal issues a temporary PASSWORD instead of a set-password link,
    and the model was dropped in the migration that follows this one. A
    historical migration must still import and run against an empty database
    (CI builds the test DB by replaying all of them), so the callable it names
    has to resolve — it is never actually called, since the table it defaults a
    column on is created and then dropped.
    """
    return secrets.token_hex(16)


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_add_parent_sms_opt_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentSessionToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "token",
                    models.CharField(default=_fresh_token, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="session_tokens", to="students.parent"
                    ),
                ),
            ],
            options={
                "db_table": "parent_session_tokens",
                "indexes": [
                    models.Index(fields=["token"], name="parent_sess_token_bc198f_idx"),
                    models.Index(fields=["expires_at"], name="parent_sess_expires_1e9375_idx"),
                ],
            },
        ),
    ]
