# Generated by Django 6.0.6 on 2026-07-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_add_parent_session_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="two_factor_backup_codes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Hashed one-time backup codes (list of sha256 hex strings). Consumed on use.",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="two_factor_enabled",
            field=models.BooleanField(
                default=False, help_text="True once the user has confirmed enrolment by entering a valid TOTP code."
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="two_factor_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Base32-encoded TOTP shared secret. Empty when 2FA is not set up.",
                max_length=64,
            ),
        ),
    ]
