# Generated by Django 6.1 on 2026-08-26 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0007_add_teacher_two_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(
                blank=True,
                help_text="Curso escolar, p. ej. «3º Primaria». Texto libre.",
                max_length=60,
                verbose_name="Curso",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="observations",
            field=models.TextField(
                blank=True,
                help_text="Notas libres: preferencia de horario, peticiones, etc.",
                verbose_name="Observaciones",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="waiting_contact_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Contacto (padre/madre)"),
        ),
        migrations.AddField(
            model_name="student",
            name="waiting_contact_phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Móvil de contacto"),
        ),
        migrations.AlterField(
            model_name="student",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="students.group",
            ),
        ),
    ]
