# Generated by Django 6.1 on 2026-08-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0008_student_course_student_observations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="max_students",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Soft limit on active enrolled students. 0 means no cap.",
                verbose_name="Cupo máximo",
            ),
        ),
    ]
