# Generated by Django 6.1 on 2026-08-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0009_alter_group_max_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="waiting_priority",
            field=models.BooleanField(
                default=False,
                help_text="Jumps ahead of the FIFO order on the waiting list. Set when a family should be offered the next free spot regardless of how long others have waited (a sibling, a returning student).",
                verbose_name="Prioritario",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
