# Generated by Django 6.1 on 2026-08-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0010_student_waiting_priority_alter_student_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="two_factor_last_counter",
            field=models.BigIntegerField(
                blank=True,
                help_text="Highest TOTP time-step already accepted. Rejects replay of a code that is still inside its validity window (RFC 6238 §5.2).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="two_factor_backup_codes",
            field=models.JSONField(
                blank=True, default=list, help_text="Hashed one-time backup codes. Consumed on use."
            ),
        ),
    ]
