# Generated by Django 6.1 on 2026-09-01 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0011_two_factor_replay_counter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Grupo", "verbose_name_plural": "Grupos"},
        ),
        migrations.AlterModelOptions(
            name="parent",
            options={"verbose_name": "Padre/Tutor", "verbose_name_plural": "Padres y tutores"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Alumno", "verbose_name_plural": "Alumnos"},
        ),
        migrations.AlterModelOptions(
            name="studentparent",
            options={"verbose_name": "Vínculo alumno–familiar", "verbose_name_plural": "Vínculos alumno–familiar"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "Profesor", "verbose_name_plural": "Profesores"},
        ),
    ]
