# Generated by Django 6.1 on 2026-09-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0012_alter_group_options_alter_parent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Hash de la contraseña del portal de familias. Vacío hasta que el padre/tutor la crea.",
                max_length=128,
                verbose_name="Contraseña del portal",
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="portal_invite_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Invitación al portal enviada"),
        ),
    ]
