# Generated by Django 6.1 on 2026-09-03 05:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0013_parent_password_parent_portal_invite_sent_at"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="group",
            name="groups_group_n_2d53de_idx",
        ),
        migrations.RemoveIndex(
            model_name="group",
            name="groups_teacher_f856b2_idx",
        ),
        migrations.RemoveIndex(
            model_name="parent",
            name="parents_dni_947d62_idx",
        ),
        migrations.RemoveIndex(
            model_name="parentsessiontoken",
            name="parent_sess_token_bc198f_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_group_i_234511_idx",
        ),
        migrations.RemoveIndex(
            model_name="teacher",
            name="teachers_email_87e41d_idx",
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(django.db.models.functions.text.Upper("email"), name="parents_email_upper_idx"),
        ),
    ]
