# Generated by Django 6.1 on 2026-09-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0014_remove_group_groups_group_n_2d53de_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="parentsessiontoken",
            name="parent_sess_expires_1e9375_idx",
        ),
        migrations.AddField(
            model_name="parent",
            name="temporary_password",
            field=models.CharField(
                blank=True,
                help_text="Hash de la contraseña temporal enviada por email. Se borra en cuanto el padre/tutor elige la suya.",
                max_length=128,
                verbose_name="Contraseña temporal",
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="temporary_password_issued_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Contraseña temporal enviada"),
        ),
        migrations.DeleteModel(
            name="ParentSessionToken",
        ),
    ]
