# Generated by Django 6.1 on 2026-09-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0015_remove_parentsessiontoken_parent_sess_expires_1e9375_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="portal_credential_changed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Credencial del portal cambiada"),
        ),
    ]
