# Generated by Django 6.1 on 2026-09-03

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the redundant case-SENSITIVE b-tree on `parents.email`.

    Every lookup on the column is `email__iexact` (the parent-portal login,
    `_parent_by_email`, `send_email --recipient`, `seed_demo_parents`), which
    Postgres renders as `UPPER(email::text) = UPPER(%s)` and answers from
    `parents_email_upper_idx`. The remaining readers are `exclude(email="")`
    and `email__icontains`, neither of which a b-tree on the raw column can
    serve. So this index answered nothing and charged every Parent insert and
    update for the privilege.
    """

    dependencies = [
        ("students", "0016_parent_portal_credential_changed_at"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="parent",
            name="parents_email_346afe_idx",
        ),
    ]
