# Generated by Django 6.1 on 2026-09-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0017_remove_parent_parents_email_346afe_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="pickup_authorized",
            field=models.TextField(
                blank=True,
                help_text="Personas autorizadas a recoger al alumno: nombre y DNI (opcional), una por línea.",
                verbose_name="Autorizados para la recogida",
            ),
        ),
    ]
