# Generated by Django 6.0.6 on 2026-07-02 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_qa_backlog_and_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("todo_completed", "Tarea completada"),
                    ("payment_completed", "Pago completado"),
                    ("student_enrolled", "Alumno matriculado"),
                    ("teacher_created", "Profesor creado"),
                    ("group_created", "Grupo creado"),
                    ("group_updated", "Grupo actualizado"),
                    ("config_updated", "Configuración actualizada"),
                    ("payment_created", "Pago creado"),
                    ("email_sent", "Email enviado"),
                    ("schedule_updated", "Horario actualizado"),
                    ("waiting_list_added", "Añadido a lista de espera"),
                    ("waiting_list_assigned", "Asignado desde lista de espera"),
                    ("waiting_list_spot_open", "Hueco disponible"),
                    ("sheets_exported", "Exportación a Google Sheets"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable actor tag, retained even if the user is later deleted.",
                        max_length=200,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update"), ("delete", "Delete")], max_length=10
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=64)),
                ("object_label", models.CharField(blank=True, max_length=300)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="audit_logs_created_43fcd6_idx"),
                    models.Index(fields=["model", "object_id"], name="audit_logs_model_fdf4ea_idx"),
                    models.Index(fields=["actor"], name="audit_logs_actor_i_0badd2_idx"),
                ],
            },
        ),
    ]
