# Generated by Django 6.0.7 on 2026-07-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_audit_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunFridayScheduledSend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipients", models.JSONField(default=list)),
                ("day_name", models.CharField(max_length=20)),
                ("day_number", models.PositiveSmallIntegerField()),
                ("month", models.CharField(max_length=20)),
                ("start_time", models.CharField(max_length=5)),
                ("end_time", models.CharField(max_length=5)),
                ("activity_description", models.TextField()),
                ("minimum_age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("maximum_age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("meeting_point", models.CharField(blank=True, max_length=255, null=True)),
                ("scheduled_for", models.DateTimeField(db_index=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fun_friday_scheduled_sends",
                "ordering": ["scheduled_for"],
            },
        ),
    ]
