# Generated by Django 6.1 on 2026-08-26 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_funfridayscheduledsend"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qaconfiguration",
            options={"verbose_name": "Configuración QA", "verbose_name_plural": "Configuración QA"},
        ),
    ]
