# Generated by Django 6.1 on 2026-08-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_historylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="backlogtask",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="El tester ha comprobado que el ticket está correcto.",
                verbose_name="desarrollado",
            ),
        ),
    ]
