# Generated by Django 6.1 on 2026-08-30 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_backlogtask_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Abierto"), ("in_progress", "En progreso"), ("done", "Hecho")],
                        default="open",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="Opcional — fecha en la que debería estar terminado.",
                        null=True,
                        verbose_name="Fecha límite",
                    ),
                ),
                ("created_by", models.CharField(default="anonymous", max_length=100, verbose_name="Creado por")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Desarrollo",
                "verbose_name_plural": "Desarrollos",
                "db_table": "features",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="backlogtask",
            name="feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="core.feature",
                verbose_name="Desarrollo",
            ),
        ),
    ]
