# Generated by Django 6.1 on 2026-09-01 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_feature_backlogtask_feature"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Registros de auditoría",
            },
        ),
        migrations.AlterModelOptions(
            name="backlogtask",
            options={"ordering": ["-created_at"], "verbose_name": "Tarea de QA", "verbose_name_plural": "Tareas de QA"},
        ),
        migrations.AlterModelOptions(
            name="funfridayattendance",
            options={
                "ordering": ["-date"],
                "verbose_name": "Asistencia Fun Friday",
                "verbose_name_plural": "Asistencias Fun Friday",
            },
        ),
        migrations.AlterModelOptions(
            name="funfridayscheduledsend",
            options={
                "ordering": ["scheduled_for"],
                "verbose_name": "Envío Fun Friday programado",
                "verbose_name_plural": "Envíos Fun Friday programados",
            },
        ),
        migrations.AlterModelOptions(
            name="historylog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Entrada de historial",
                "verbose_name_plural": "Historial de actividad",
            },
        ),
        migrations.AlterModelOptions(
            name="scheduleslot",
            options={
                "ordering": ["row", "day", "col"],
                "verbose_name": "Franja horaria",
                "verbose_name_plural": "Franjas horarias",
            },
        ),
        migrations.AlterModelOptions(
            name="todoitem",
            options={
                "ordering": ["due_date", "created_at"],
                "verbose_name": "Tarea pendiente",
                "verbose_name_plural": "Tareas pendientes",
            },
        ),
    ]
