# Generated by Django 6.1 on 2026-09-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_auditlog_options_alter_backlogtask_options_and_more"),
        ("students", "0012_alter_group_options_alter_parent_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="funfridayattendance",
            index=models.Index(fields=["date"], name="fun_friday__date_c25bdb_idx"),
        ),
    ]
