# Generated by Django 6.1 on 2026-09-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_funfridayattendance_fun_friday__date_c25bdb_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="qaconfiguration",
            name="ready_for_prod",
            field=models.BooleanField(default=False, verbose_name="Versión lista para producción"),
        ),
    ]
