# Generated by Django 6.1 on 2026-09-03 05:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_qaconfiguration_ready_for_prod"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_actor_i_0badd2_idx",
        ),
    ]
