# Generated by Django 6.1 on 2026-09-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_remove_auditlog_audit_logs_actor_i_0badd2_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[("create", "Creación"), ("update", "Modificación"), ("delete", "Eliminación")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="backlogtask",
            name="priority",
            field=models.CharField(
                choices=[("low", "Baja"), ("medium", "Media"), ("high", "Alta")], default="medium", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="backlogtask",
            name="status",
            field=models.CharField(
                choices=[("open", "Abierta"), ("in_progress", "En progreso"), ("done", "Hecha")],
                default="open",
                max_length=15,
            ),
        ),
    ]
