# Generated by Django 6.1 on 2026-09-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_auditlog_action_alter_backlogtask_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("todo_completed", "Tarea completada"),
                    ("payment_completed", "Pago completado"),
                    ("student_enrolled", "Alumno matriculado"),
                    ("teacher_created", "Profesor creado"),
                    ("group_created", "Grupo creado"),
                    ("group_updated", "Grupo actualizado"),
                    ("config_updated", "Configuración actualizada"),
                    ("payment_created", "Pago creado"),
                    ("email_sent", "Email enviado"),
                    ("email_scheduled", "Email programado"),
                    ("schedule_updated", "Horario actualizado"),
                    ("waiting_list_added", "Añadido a lista de espera"),
                    ("waiting_list_assigned", "Asignado desde lista de espera"),
                    ("waiting_list_spot_open", "Hueco disponible"),
                    ("sheets_exported", "Exportación a Google Sheets"),
                    ("enrollment_modality_changed", "Modalidad de pago cambiada"),
                ],
                max_length=30,
            ),
        ),
    ]
