# Generated by Django 6.1 on 2026-09-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_qaconfiguration_drive_uploads_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleDriveCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "account_email",
                    models.CharField(
                        blank=True,
                        help_text="La cuenta que autorizó el acceso; es la propietaria de los archivos subidos.",
                        max_length=254,
                        verbose_name="Cuenta de Google conectada",
                    ),
                ),
                (
                    "refresh_token_encrypted",
                    models.TextField(blank=True, verbose_name="Token de actualización (cifrado)"),
                ),
                ("connected_by", models.CharField(blank=True, max_length=254, verbose_name="Autorizado por")),
                ("connected_at", models.DateTimeField(blank=True, null=True, verbose_name="Fecha de autorización")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Credencial de Google Drive",
                "verbose_name_plural": "Credencial de Google Drive",
                "db_table": "google_drive_credential",
            },
        ),
    ]
