# Generated by Django 6.1 on 2026-09-18 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_googledrivecredential"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qaconfiguration",
            name="drive_uploads_enabled",
        ),
    ]
