# Generated by Django 6.0.6 on 2026-07-02 17:07

import datetime
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_enrollment_enrollments_academi_615a2d_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rent", "Alquiler"),
                            ("salaries", "Salarios"),
                            ("supplies", "Material"),
                            ("utilities", "Suministros"),
                            ("marketing", "Marketing"),
                            ("software", "Software / Suscripciones"),
                            ("insurance", "Seguros"),
                            ("taxes", "Impuestos"),
                            ("other", "Otros"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("expense_date", models.DateField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurring_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Day of the month (1–28) when a recurring template should materialise a concrete Expense.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_children",
                        to="billing.expense",
                    ),
                ),
            ],
            options={
                "db_table": "expenses",
                "ordering": ["-expense_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["expense_date"], name="expenses_expense_43600a_idx"),
                    models.Index(fields=["category"], name="expenses_categor_a6f264_idx"),
                    models.Index(fields=["is_recurring"], name="expenses_is_recu_7c3a89_idx"),
                ],
            },
        ),
    ]
