# Generated by Django 6.0.6 on 2026-07-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_add_expense_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_intent",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe PaymentIntent id; populated when the webhook fires on session completion.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe Checkout session id; populated when a payment link is issued.",
                max_length=200,
            ),
        ),
    ]
