# Generated by Django 6.0.6 on 2026-07-03 06:02

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_add_payment_stripe_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="returning_student_enrollment_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.00"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Estudiante recurrente (€ fijo sobre la matrícula)",
            ),
        ),
    ]
