# Generated by Django 6.0.7 on 2026-07-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_add_returning_student_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="recurring_frequency",
            field=models.CharField(
                choices=[("monthly", "Mensual"), ("yearly", "Anual"), ("weekly", "Semanal")],
                default="monthly",
                help_text="Cadence of a recurring template: monthly, yearly or weekly.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="recurring_month",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Month (1–12) when a yearly template should materialise.", null=True
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="recurring_weekdays",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated weekday ints (0=Mon … 6=Sun) for weekly templates.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="recurring_day",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Day of the month (1–28). Used by monthly + yearly templates.", null=True
            ),
        ),
    ]
