# Generated by Django 6.1 on 2026-08-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_expense_recurring_frequency_expense_recurring_month_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={"verbose_name": "Matrícula", "verbose_name_plural": "Matrículas"},
        ),
        migrations.AlterModelOptions(
            name="enrollmenttype",
            options={"verbose_name": "Tipo de matrícula", "verbose_name_plural": "Tipos de matrícula"},
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={
                "ordering": ["-expense_date", "-created_at"],
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Pago", "verbose_name_plural": "Pagos"},
        ),
        migrations.AlterField(
            model_name="expense",
            name="recurring_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Day of the month (1–31). Used by monthly + yearly templates. Days past the end of a short month fall back to that month's last day, so 31 means 'last day of the month'.",
                null=True,
            ),
        ),
    ]
