# Generated by Django 6.1 on 2026-08-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0008_enrollment_type_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("active", "Activa"),
                    ("finished", "Finalizada"),
                    ("cancelled", "Cancelada"),
                    ("suspended", "Suspendida"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("completed", "Completado"),
                    ("failed", "Fallido"),
                    ("cancelled", "Cancelado"),
                    ("refunded", "Reembolsado"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("enrollment", "Matrícula"),
                    ("monthly", "Mensualidad"),
                    ("quarterly", "Trimestre"),
                    ("other", "Otro"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
    ]
