# Generated by Django 6.1 on 2026-09-03 05:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_payment_payment_status_due_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="enrollment",
            name="enrollments_student_379f04_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_student_5b85b3_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_parent__d631d3_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_enrollm_7d7109_idx",
        ),
    ]
