# Generated by Django 6.1 on 2026-09-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0011_remove_enrollment_enrollments_student_379f04_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmenttype",
            name="name",
            field=models.CharField(
                choices=[
                    ("new_student", "Nuevo estudiante"),
                    ("returning_student", "Antiguo estudiante"),
                    ("adults", "Adulto"),
                    ("special", "Especial"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
