# Generated by Django 6.1 on 2026-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0013_siteconfiguration_academy_fields"),
        ("students", "0017_remove_parent_parents_email_346afe_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="receipt_number",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20, verbose_name="Número de recibo"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="receipt_offset",
            field=models.PositiveIntegerField(default=632, verbose_name="Último recibo emitido en papel ese año"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="receipt_offset_year",
            field=models.PositiveIntegerField(default=2026, verbose_name="Año con numeración heredada de recibos"),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("receipt_number", ""), _negated=True),
                fields=("receipt_number",),
                name="unique_receipt_number",
            ),
        ),
    ]
