# Generated by Django 6.1 on 2026-09-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0014_payment_receipt_number_and_more"),
        ("students", "0018_student_pickup_authorized"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="payment",
            name="unique_receipt_number",
            constraint=models.UniqueConstraint(
                condition=models.Q(("receipt_number", ""), _negated=True),
                fields=("receipt_number",),
                name="unique_receipt_number",
                violation_error_message="Ese número de recibo ya está asignado a otro pago.",
            ),
        ),
    ]
