# Generated by Django 6.1 on 2026-09-13 18:48

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0015_alter_payment_unique_receipt_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="part_time_child_monthly_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("32.00"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Mensualidad infantil",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("full_time", "2 días/semana"),
                    ("part_time", "1 día/semana"),
                    ("part_time_child", "Infantil (1 día/semana)"),
                    ("adult_group", "Adultos (1 día/semana)"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
    ]
